using System.Security.Cryptography;
using BE.Core.Authorization;
using BE.Core.Data;
using BE.Core.DTOs.HumanResources;
using BE.Core.Entities.AD;
using BE.Core.Entities.MD;
using BE.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace BE.Service.Services
{
    public class HumanResourceService
    {
        private readonly AppDbContext _db; private readonly IPermissionService _permissions;
        public HumanResourceService(AppDbContext db, IPermissionService permissions) { _db = db; _permissions = permissions; }
        public async Task<object> Summary() { var orgs = await _db.MdOrganizes.CountAsync(); var employees = await _db.AdAccounts.CountAsync(); var active = await _db.AdAccounts.CountAsync(x => x.IsActive); var byOrg = await (from o in _db.MdOrganizes join a in _db.AdAccounts on o.Id equals a.OrgId into users select new { o.Id, o.Name, Count = users.Count() }).OrderByDescending(x => x.Count).ToListAsync(); return new { organizationCount = orgs, employeeCount = employees, activeAccountCount = active, lockedAccountCount = employees - active, employeesByOrganization = byOrg }; }
        public Task<List<object>> Organizations() => _db.MdOrganizes.AsNoTracking().OrderBy(x => x.OrderNumber).ThenBy(x => x.Name).Select(x => (object)new { x.Id, x.PId, x.Name, x.OrderNumber, x.Expanded, x.IsActive, x.Notes, employeeCount = _db.AdAccounts.Count(a => a.OrgId == x.Id) }).ToListAsync();
        public async Task<object> CreateOrganization(OrganizationRequest r, string actor) { if (!string.IsNullOrEmpty(r.ParentId) && !await _db.MdOrganizes.AnyAsync(x => x.Id == r.ParentId)) throw new ArgumentException("Phòng ban cha không tồn tại."); var now = DateTime.UtcNow; var e = new MdOrganize { Id = Guid.NewGuid().ToString("N"), PId = r.ParentId ?? string.Empty, Name = r.Name.Trim(), OrderNumber = r.OrderNumber, Expanded = true, IsActive = r.IsActive, Notes = r.Notes, CreateBy = actor, CreateDate = now, UpdateBy = actor, UpdateDate = now }; if (e.Name.Length == 0) throw new ArgumentException("Tên phòng ban không được trống."); _db.Add(e); await _db.SaveChangesAsync(); return e; }
        public async Task UpdateOrganization(string id, OrganizationRequest r, string actor) { var e = await Org(id); if (r.ParentId == id || await IsDescendant(id, r.ParentId)) throw new InvalidOperationException("Không thể tạo vòng lặp cây tổ chức."); e.PId = r.ParentId ?? string.Empty; e.Name = r.Name.Trim(); e.OrderNumber = r.OrderNumber; e.IsActive = r.IsActive; e.Notes = r.Notes; e.UpdateBy = actor; e.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task MoveOrganization(string id, MoveOrganizationRequest r, string actor) { var e = await Org(id); if (r.ParentId == id || await IsDescendant(id, r.ParentId)) throw new InvalidOperationException("Không thể chuyển phòng ban vào cây con của chính nó."); if (!string.IsNullOrEmpty(r.ParentId) && !await _db.MdOrganizes.AnyAsync(x => x.Id == r.ParentId)) throw new ArgumentException("Phòng ban cha không tồn tại."); e.PId = r.ParentId ?? string.Empty; e.OrderNumber = r.OrderNumber; e.UpdateBy = actor; e.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task DeleteOrganization(string id) { if (await _db.MdOrganizes.AnyAsync(x => x.PId == id)) throw new InvalidOperationException("Phòng ban còn đơn vị con."); if (await _db.AdAccounts.AnyAsync(x => x.OrgId == id)) throw new InvalidOperationException("Phòng ban đang có nhân sự."); _db.Remove(await Org(id)); await _db.SaveChangesAsync(); }
        private async Task<MdOrganize> Org(string id) => await _db.MdOrganizes.FindAsync(id) ?? throw new KeyNotFoundException("Không tìm thấy phòng ban.");
        private async Task<bool> IsDescendant(string root, string? candidate) { var current = candidate; var seen = new HashSet<string>(); while (!string.IsNullOrEmpty(current) && seen.Add(current)) { if (current == root) return true; current = await _db.MdOrganizes.Where(x => x.Id == current).Select(x => x.PId).FirstOrDefaultAsync(); } return false; }

        public Task<List<object>> Titles() => _db.MdTitles.AsNoTracking().OrderBy(x => x.OrderNumber).Select(x => (object)new { x.Code, x.Name, x.Notes, x.OrderNumber, x.IsActive, employeeCount = _db.AdAccounts.Count(a => a.TitleCode == x.Code) }).ToListAsync();
        public async Task<object> CreateTitle(TitleRequest r, string actor) { var code = r.Code.Trim().ToUpperInvariant(); if (await _db.MdTitles.AnyAsync(x => x.Code == code)) throw new ArgumentException("Mã chức danh đã tồn tại."); var now = DateTime.UtcNow; var e = new MdTitle { Code = code, Name = r.Name.Trim(), Notes = r.Notes ?? string.Empty, OrderNumber = r.OrderNumber, IsActive = r.IsActive, CreateBy = actor, CreateDate = now, UpdateBy = actor, UpdateDate = now }; _db.Add(e); await _db.SaveChangesAsync(); return e; }
        public async Task UpdateTitle(string code, TitleRequest r, string actor) { var e = await Title(code); e.Name = r.Name.Trim(); e.Notes = r.Notes ?? string.Empty; e.OrderNumber = r.OrderNumber; e.IsActive = r.IsActive; e.UpdateBy = actor; e.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task DeleteTitle(string code) { if (await _db.AdAccounts.AnyAsync(x => x.TitleCode == code)) throw new InvalidOperationException("Chức danh đang được sử dụng."); _db.Remove(await Title(code)); await _db.SaveChangesAsync(); }
        private async Task<MdTitle> Title(string code) => await _db.MdTitles.FindAsync(code) ?? throw new KeyNotFoundException("Không tìm thấy chức danh.");

        public async Task<object> Employees(string? org, string? title, bool? active, string? keyword, int page, int pageSize) { page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 100); var q = from a in _db.AdAccounts.AsNoTracking() join o in _db.MdOrganizes on a.OrgId equals o.Id join t in _db.MdTitles on a.TitleCode equals t.Code select new { a.UserName, a.FullName, a.Email, a.Phone, a.Address, a.OrgId, organizationName = o.Name, a.TitleCode, titleName = t.Name, a.IsActive, a.MustChangePassword, a.LastLoginAt, a.CreateDate }; if (!string.IsNullOrEmpty(org)) q = q.Where(x => x.OrgId == org); if (!string.IsNullOrEmpty(title)) q = q.Where(x => x.TitleCode == title); if (active.HasValue) q = q.Where(x => x.IsActive == active); if (!string.IsNullOrWhiteSpace(keyword)) { var k = keyword.Trim(); q = q.Where(x => x.UserName.Contains(k) || x.FullName.Contains(k) || x.Email.Contains(k)); } var total = await q.CountAsync(); var items = await q.OrderBy(x => x.FullName).Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(); return new { items, page, pageSize, totalItems = total, totalPages = (int)Math.Ceiling(total / (double)pageSize) }; }
        public async Task<object> Employee(string user) { var a = await Account(user); var org = await _db.MdOrganizes.FindAsync(a.OrgId); var title = await _db.MdTitles.FindAsync(a.TitleCode); return new { a.UserName, a.FullName, a.Email, a.Phone, a.Address, a.OrgId, organizationName = org?.Name, a.TitleCode, titleName = title?.Name, a.IsActive, a.MustChangePassword, a.LastLoginAt, a.CreateDate, a.UpdateDate }; }
        public async Task<object> CreateEmployee(EmployeeRequest r, string actor) { await ValidateOrgTitle(r.OrganizationId, r.TitleCode); if (await _db.AdAccounts.AnyAsync(x => x.UserName == r.UserName || x.Email == r.Email)) throw new ArgumentException("Username hoặc email đã tồn tại."); var password = GeneratePassword(); var now = DateTime.UtcNow; var a = new AdAccount { UserName = r.UserName.Trim(), Password = BCrypt.Net.BCrypt.HashPassword(password), FullName = r.FullName.Trim(), Email = r.Email.Trim(), Phone = r.Phone.Trim(), Address = r.Address.Trim(), OrgId = r.OrganizationId, TitleCode = r.TitleCode, PermissionJson = null, RoleCodes = null, IsActive = true, MustChangePassword = true, TokenVersion = 1, CreateBy = actor, CreateDate = now, UpdateBy = actor, UpdateDate = now }; _db.Add(a); await _db.SaveChangesAsync(); return new { a.UserName, a.FullName, a.Email, temporaryPassword = password, a.MustChangePassword }; }
        public async Task UpdateEmployee(string user, UpdateEmployeeRequest r, string actor) { await ValidateOrgTitle(r.OrganizationId, r.TitleCode); var a = await Account(user); if (await _db.AdAccounts.AnyAsync(x => x.Email == r.Email && x.UserName != user)) throw new ArgumentException("Email đã tồn tại."); a.FullName = r.FullName.Trim(); a.Email = r.Email.Trim(); a.Phone = r.Phone.Trim(); a.Address = r.Address.Trim(); a.OrgId = r.OrganizationId; a.TitleCode = r.TitleCode; a.TokenVersion++; a.UpdateBy = actor; a.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task Transfer(string user, TransferEmployeeRequest r, string actor) { if (!await _db.MdOrganizes.AnyAsync(x => x.Id == r.OrganizationId && x.IsActive)) throw new ArgumentException("Phòng ban không hợp lệ."); var a = await Account(user); a.OrgId = r.OrganizationId; a.TokenVersion++; a.UpdateBy = actor; a.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task ChangeTitle(string user, ChangeTitleRequest r, string actor) { if (!await _db.MdTitles.AnyAsync(x => x.Code == r.TitleCode && x.IsActive)) throw new ArgumentException("Chức danh không hợp lệ."); var a = await Account(user); a.TitleCode = r.TitleCode; a.TokenVersion++; a.UpdateBy = actor; a.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task ChangeStatus(string user, ChangeStatusRequest r, string actor) { if (user == actor && !r.IsActive) throw new InvalidOperationException("Không thể tự khóa tài khoản đang đăng nhập."); var a = await Account(user); a.IsActive = r.IsActive; a.TokenVersion++; a.UpdateBy = actor; a.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); }
        public async Task<object> ResetPassword(string user, string actor) { var a = await Account(user); var password = GeneratePassword(); a.Password = BCrypt.Net.BCrypt.HashPassword(password); a.MustChangePassword = true; a.TokenVersion++; a.UpdateBy = actor; a.UpdateDate = DateTime.UtcNow; await _db.SaveChangesAsync(); return new { a.UserName, temporaryPassword = password }; }
        private async Task<AdAccount> Account(string user) => await _db.AdAccounts.FindAsync(user) ?? throw new KeyNotFoundException("Không tìm thấy tài khoản.");
        private async Task ValidateOrgTitle(string org, string title) { if (!await _db.MdOrganizes.AnyAsync(x => x.Id == org && x.IsActive)) throw new ArgumentException("Phòng ban không hợp lệ."); if (!await _db.MdTitles.AnyAsync(x => x.Code == title && x.IsActive)) throw new ArgumentException("Chức danh không hợp lệ."); }
        private static string GeneratePassword() { const string chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$"; return new string(Enumerable.Range(0, 12).Select(_ => chars[RandomNumberGenerator.GetInt32(chars.Length)]).ToArray()); }

        public async Task<PermissionDocument> GetPermission(string type, string id) { var json = type switch { "organization" => (await Org(id)).PermissionJson, "title" => (await Title(id)).PermissionJson, "employee" => (await Account(id)).PermissionJson, _ => throw new ArgumentException("Đối tượng phân quyền không hợp lệ.") }; return _permissions.ParseAndValidate(json); }
        public async Task SavePermission(string type, string id, PermissionDocument doc, string actor) { var json = _permissions.SerializeAndValidate(doc); switch (type) { case "organization": var o = await Org(id); o.PermissionJson = json; o.UpdateBy = actor; o.UpdateDate = DateTime.UtcNow; break; case "title": var t = await Title(id); t.PermissionJson = json; t.UpdateBy = actor; t.UpdateDate = DateTime.UtcNow; break; case "employee": var a = await Account(id); a.PermissionJson = json; a.TokenVersion++; a.UpdateBy = actor; a.UpdateDate = DateTime.UtcNow; break; default: throw new ArgumentException("Đối tượng phân quyền không hợp lệ."); } await _db.SaveChangesAsync(); }
    }
}
